### ISSUE TITLE
Fake, Doesn't Work

### ISSUE THREAD

**Issue by ghost** [chaarlottte/capsolver-generator-checker#1]

**Comment by laika-cosmonaut** [comment]
It works fine. If you’re having trouble getting it set up, or if you’re encountering errors, feel free to ask about that.

**Comment by ghost** [comment]
> It works fine. If you’re having trouble getting it set up, or if you’re encountering errors, feel free to ask about that.

you sure?
It doesn't email verify

<img width="559" alt="image" src="https://user-images.githubusercontent.com/64490610/219958456-e39cb5af-3974-4a0f-8b48-cf35d4d23ded.png">

**Comment by ghost** [comment]
Hm, nevermind, after a few minutes, it received the code. It was weird because I tried signing up myself, but didn't get the code...

I guess a lot of people are using it and they might be holding up their servers.

**Comment by laika-cosmonaut** [comment]
They’ve been blocking certain email domains. You might have to change GMAILNATOR to INBOXKITTEN in the config.

**Comment by ghost** [comment]
Thanks!
