### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dark987441** [chaarlottte/capsolver-generator-checker#4]
[ERROR] argument of type 'NoneType' is not iterable

![Screenshot_4](https://user-images.githubusercontent.com/124207654/220720272-648468c8-5c22-47bf-b530-4744762b2526.png)

**Comment by laika-cosmonaut** [comment]
Change the tempmail service to INBOXKITTEN. It's also, like, halfway patched atm. I'll be releasing a fix soon, don't worry :)

**Comment by dark987441** [comment]
{'statusCode': 400, 'message': 'system error', 'error': 'Bad Request'}

00:31:19 | WORKER-010 | ! > [FAIL] Unknown error on signup. Status code: 400

![Screenshot_1](https://user-images.githubusercontent.com/124207654/220763757-cf3bb8d3-2e42-4697-bf14-6e44ab1f014d.png)

**Comment by dark987441** [comment]
???

**Comment by laika-cosmonaut** [comment]
The method does seem to be patched, unfortunately. I’ll be archiving this repo shortly.
